name: CI/CD - Package & IIS deploy
on:
  workflow_dispatch:
    inputs:
      CLIENT:
        type: choice
        description: Make a choice and move on
        options:
        - Abc
        - Absa
        - BankOfAfrica
        - BankOfIndia
        - Baroda
        - Bou
        - Brac
        - Cairobank
        - Development
        - Dfcu
        - Dtb
        - Ecobank
        - Equity
        - Exim
        - FinanceTrust
        - Finca
        - GTBank
        - HousingFinance
        - Kcb
        - Laboremus
        - Mcb
        - Ncba
        - OpportunityBank
        - Orient
        - Pride
        - Production
        - SmileId
        - Staging
        - Standbic
        - StanCart
        - Streamline
        - Test
        - TopFinance
        - Tropical
        - Uba
        - Ugafode
        - Yako
      CLIENT_ENV:
        type: choice
        description: Select environment
        options:
        - Prod
        - Uat
        - Test
        - Sit
      DOWNLOAD_PACKAGE:
        type: choice
        description: Should package?
        default: 'Skip'
        options:
        - Download
        - Skip
      DEPLOY_IIS:
        type: choice
        description: Should IIS?
        default: 'Skip'
        options:
        - Deploy
        - Skip
jobs:
  RUN_PROCESS:
    uses: ./.github/workflows/az-webapps-dotnet-core-root.yml
    with:
      DOTNET_VERSION: "2.1.x"
      CLIENT: "${{ github.event.inputs.CLIENT }}"
      CLIENT_ENV: "${{ github.event.inputs.CLIENT_ENV }}"
      DOWNLOAD_PACKAGE: "${{ github.event.inputs.DOWNLOAD_PACKAGE }}"
      DEPLOY_IIS: "${{ github.event.inputs.DEPLOY_IIS }}"
      PROJECT_ROOT_DIRECTORY: "Laboremus_auth_api"
      SITE_NAME: "Bou_NationalIdVerification_Auth_Ui_React"
      WEBDEPLOY_USER: "kevin"
      WEBDEPLOY_PASSWORD: "${{ secrets.WEBDEPLOY_PASSWORD }}"
      SERVER_IP: "154.0.128.234"
      SERVER_PORT: "18172"
    secrets:
      NUGET_URL_pass: https://pkgs.dev.azure.com/laboremus-uganda/LUG/_packaging/LugNuGetFeed/nuget/v3/index.json
      NUGET_TOKEN_pass: ${{ secrets.NUGET_TOKEN }}
